name: build
on: pull_request
jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Network 
        run: docker network create testnet
      - name: yarn install and build
        run: docker-compose -f docker-compose.yml run front sh -c 'yarn install && yarn build'